### PR TITLE
Made sample names a category to preserve order in plot.CodonMutTypes

### PR DESCRIPTION
**Pull request by ajgreaney**

### CODE REVIEW

**Comment by jbloom** [comment]
@ajgreaney: Your pull request failed the tests. See the Travis CI report here:
https://travis-ci.org/jbloomlab/dms_tools2/builds/535495787?utm_source=github_status&utm_medium=notification

It doesn't appear to be due to your changes. Rather, it appears that in `scipy` version 1.3.0, they have deprecated `import scipy.misc.factorial` (see [here](https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#backwards-incompatible-changes)), and this causes a problem with `plotnine`. Note that this issue has already been reported to `plotnine` (see [here](https://github.com/has2k1/plotnine/issues/275)), so we don't need to do anything.

To get your build to fix, we need to specify to use `scipy` less than version 1.3.0 at least for now. This can be done by modifying [this line](https://github.com/ajgreaney/dms_tools2/blob/master/setup.py#L64) in `dms_tools2` `setup.py` to read:
```
scipy>=1.0,<1.3
```

Make that additional change and push to your fork, and then lets see if your pull request passes the tests.

**Comment by jbloom** [comment]
@ajgreaney: Looks good and passes all tests. Are there any other plotting functions for which need a similar change, or should I go ahead and merge this and make it the new version `2.4.12`?

**Comment by ajgreaney** [comment]
@jbloom Not every plotting function uses sample names as a category. The two that do not but for which it might be useful are `plotReadStats` and `plotBCStats`, but it seems likely we will not be using these functions to make journal-quality figures, and I have also not used these functions myself so I'm not sure if the change is necessary.  If you think I should change these too, I will do it and then push my changes.

**Comment by jbloom** [comment]
OK, I'll merge these changes and we can worry about other functions later if needed.

**Pull request merged**
