### PR TITLE
added pseudocount to raw codon counts in `syn_selection_by_codon`

### PR DESCRIPTION
**Pull request by fwelsh**

### CODE REVIEW

**Comment by jbloom** [comment]
@Frances: You should make several changes to this:

1. Make the value of the pseudocount [an optional argument](https://linux.die.net/diveintopython/html/power_of_introspection/optional_arguments.html) in the function signature, and set a reasonable default. Such as `pseudocount=0.5`. Then expand the documentation to explain what the pseudocount argument means.

2. Do **not** use the pseudocount for the Fisher's exact test. That test should be performed on the raw values as the Fisher's test already works fine with zero counts. The pseudocounts should only be used for computing the odds ratios. Implementation-wise, this probably means doing the Fisher test and then adding the pseudocount. Clearly explain this in the docs.

3. You'll have to fix so it passes the doctest (right now it fails, see [here](https://travis-ci.org/jbloomlab/dms_tools2/jobs/609461559?utm_medium=notification&utm_source=github_status)). Note that if you do point (2) above, you should be changing the odds ratios in the doctest output but **not** the P-values, since the P-value counts won't change.

**Comment by skhilton** [comment]
@jbloom, @fwelsh: Looks good to me! You might consider setting a default value of the psuedocounts, especially if you think that 0.5 is going to be the best value for the majority of use cases. You can do this by changing https://github.com/jbloomlab/dms_tools2/blob/syn_selection_updates/dms_tools2/syn_selection.py#L16 to `def syn_selection_by_codon(counts_pre, counts_post, pseudocount=0.5):`

Also, very small note, but I don't think you need the parenthesis around `df` in the function return statement. https://github.com/jbloomlab/dms_tools2/blob/syn_selection_updates/dms_tools2/syn_selection.py#L157

**Comment by jbloom** [comment]
OK, I agree with @skhilton's comments especially about default. @fwelsh, do you want to push that, and then I'll merge.

**Comment by jbloom** [comment]
@fwelsh: Sorry, one more change I realized that is also needed:

1. Can you update the version number [here](https://github.com/jbloomlab/dms_tools2/blob/master/dms_tools2/_metadata.py#L1) to `2.6.3`.

2. Can you add to the [CHANGELOG](https://github.com/jbloomlab/dms_tools2/blob/master/CHANGELOG.rst) a short explanation of the change. Then I can merge this as the new version.

**Comment by fwelsh** [comment]
Sorry I didn't notice that, but we should be set now!

**Pull request merged**
